### ISSUE TITLE
Unable to connect to Email Skill

### ISSUE THREAD

**Issue by csnarain** [microsoft/botframework-skills#262] opened 2020-06-16 14:21 UTC
I'm getting the below error when trying to connect the email skill to my VA using the Bot emulator. I tried all troubleshooting steps but it's still not working. I checked all settings (appsettings, manifest etc). Everything seems to be accurate. What could be the problem? Both the skill and the VA are running on Azure

System.Net.Http.HttpRequestException: Error invoking the skill id: "EmailSkill" at "https://{URL}/api/messages" (status is 500). 
 
 at Microsoft.Bot.Builder.Dialogs.SkillDialog.SendToSkillAsync(ITurnContext context, Activity activity, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.SkillDialog.BeginDialogAsync(DialogContext dc, Object options, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogContext.BeginDialogAsync(String dialogId, Object options, CancellationToken cancellationToken)
 at VirtualAssistant.Dialogs.MainDialog.RouteStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken) in xxxx\Repos\VirtualAssistant\VirtualAssistant\Dialogs\MainDialog.cs:line 375
 at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.OnStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.RunStepAsync(DialogContext dc, Int32 index, DialogReason reason, Object result, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.WaterfallDialog.ResumeDialogAsync(DialogContext dc, DialogReason reason, Object result, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogContext.EndDialogAsync(Object result, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.Prompt`1.ContinueDialogAsync(DialogContext dc, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
 at VirtualAssistant.Dialogs.MainDialog.OnContinueDialogAsync(DialogContext innerDc, CancellationToken cancellationToken) in xxx\Source\Repos\VirtualAssistant\VirtualAssistant\Dialogs\MainDialog.cs:line 163
 at Microsoft.Bot.Builder.Dialogs.ComponentDialog.ContinueDialogAsync(DialogContext outerDc, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogContext.ContinueDialogAsync(CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Dialogs.DialogExtensions.RunAsync(Dialog dialog, ITurnContext turnContext, IStatePropertyAccessor`1 accessor, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.ActivityHandler.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
 at VirtualAssistant.Bots.DefaultActivityHandler`1.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in xxx\Source\Repos\VirtualAssistant\VirtualAssistant\Bots\DefaultActivityHandler.cs:line 44
 at Microsoft.Bot.Solutions.Middleware.EventDebuggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Solutions.Middleware.SetLocaleMiddleware.OnTurnAsync(ITurnContext context, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.ShowTypingMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.TranscriptLoggerMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.TelemetryLoggerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.Integration.ApplicationInsights.Core.TelemetryInitializerMiddleware.OnTurnAsync(ITurnContext context, NextDelegate nextTurn, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
 at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)"

**Comment by xieofxie** [comment] 2020-06-17 01:52
Hi, have you tried running them locally? 500 could indicate an error in the skill side.
What about the url of skillHostEndpoint in VA's appsettings.json? One may forget to change it when deploying in Azure.

**Comment by csnarain** [comment] 2020-06-17 05:29
@xieofxie - Yes, that was the first thing I checked. It's pointing to my VA's azure instance only. But one thing I noticed is when I traversed to that endpoint in my browser nothing happens. Would it normally show any published skills on that endpoint?

**Comment by xieofxie** [comment] 2020-06-17 06:06
@csnarain, no, that endpoint is used for receiving replies from skill, so if you visit it via browser, it will display nothing.

Since skill is 500, could you get any logs for the cause? Like described here https://serverfault.com/questions/949418/monitoring-http-5xx-errors-in-an-azure-app-service

Can you use your email skill directly? Is it working correctly alone?

**Comment by csnarain** [comment] 2020-06-17 06:47
@xieofxie - I did check the logs of the skill on Azure and found the below error on the application logs in the service. Pls note that I'm using the email skill template from https://github.com/microsoft/botframework-skills/tree/master/skills/csharp/emailskill without modifying a single line of code


</head><body><div id="content"><div class="content-container"><h3>HTTP Error 500.0 - Internal Server Error</h3><h4>The page cannot be displayed because an internal server error has occurred.</h4></div><div class="content-container"><fieldset><h4>Most likely causes:</h4><ul> 	<li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li> 	<li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li> 	<li>IIS was not able to process configuration for the Web site or application.</li> 	<li>The authenticated user does not have permission to use this DLL.</li> 	<li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul></fieldset></div><div class="content-container"><fieldset><h4>Things you can try:</h4><ul> 	<li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li> 	<li>Check the event logs to see if any additional information was logged.</li> 	<li>Verify the permissions for the DLL.</li> 	<li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul></fieldset></div>

**Comment by csnarain** [comment] 2020-06-17 07:38
@xieofxie - Finally fixed the 500 error in the skill (some config issue). However, I'm still facing issues in the VA. Pls see below

![image](https://user-images.githubusercontent.com/9998645/84869391-98e84600-b09b-11ea-99d3-7177bdfe42ff.png)


![image](https://user-images.githubusercontent.com/9998645/84869349-8a019380-b09b-11ea-8917-0bcfa89b3512.png)

**Comment by xieofxie** [comment] 2020-06-17 08:07
From the error message, your kb id is non exist. Please check in https://www.qnamaker.ai/Home/MyServices to see if it matches the one in VA's cognitivemodels.

Do you connect your skill correctly like here https://microsoft.github.io/botframework-solutions/skills/tutorials/add-prebuilt-skill/4-connect-skill/? If the dispatch is working correctly, it should not got to qna. You could check in https://www.luis.ai/applications to verify if dispatch app has an email intent and it could be recognized correctly for utternace 'send an email'

**Comment by csnarain** [comment] 2020-06-18 15:31
@xieofxie - I finally resolved the problem. The issues were multi-fold but your inputs were very valuable in resolving the issue. Thank you!!!

**Comment by xieofxie** [comment] 2020-06-19 02:08
Good. I close it now

**Closed by xieofxie** 2020-06-19 02:08 UTC
Labels: Needs Triage, Type: Bug
